'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Play,Pause,Square,Download,Settings2,Radio} from 'lucide-react';
import {initial,type State} from '@/lib/paper-engine';
import {dashboardView,type DashboardView} from '@/lib/dashboard-view';
import {STRATEGIES,strategyInfo,strategyName,type StrategyId} from '@/lib/strategies';
import {FOREX_PAIRS} from '@/lib/forex';
import evaluation from '@/lib/strategy-evaluation.json';
import alphaEvaluation from '@/lib/momentum-alpha-evaluation.json';
import TradeScene from './trade-scene';
import Research from './research';
import TeamPanel from './team-panel';
import LearningReview from './learning-review';
import SectorPanel from './sector-panel';
import DailyStatus from './daily-status';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
const price=(n:number|null)=>n===null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:n<1?6:2}).format(n);
const signed=(n:number)=>(n>0?'+':'')+money(n);
const clock=(n:number)=>new Date(n).toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',second:'2-digit'});
const date=(n:number)=>new Date(n).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'});
type Page='live'|'pnl'|'journal'|'research'|'core'|'settings';
export default function Dashboard(){
 const [s,setS]=useState<State>(initial),[view,setView]=useState<DashboardView|null>(null),[page,setPage]=useState<Page>('live'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[signin,setSignin]=useState(false),[connected,setConnected]=useState(false),[now,setNow]=useState(0);
 const [selectedAgent,setSelectedAgent]=useState('agent-1');
 const inFlight=useRef(false),viewRef=useRef(view);useEffect(()=>{viewRef.current=view},[view]);
 const update=useCallback(async(action:string,strategy?:StrategyId,agentId?:string,reviewKey?:string,reviewNote?:string)=>{
  if(inFlight.current)return;inFlight.current=true;setBusy(true);
  try{
   const r=await fetch('/api/paper',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,strategy,agentId,reviewKey,reviewNote})});
   if(!r.headers.get('content-type')?.includes('application/json')){setSignin(true);throw new Error('Reconnect your portfolio to restore monitoring.')}
   const data=await r.json() as {state?:State;view?:DashboardView;signin?:boolean;error?:string};
   if(data.state)setS(data.state);if(data.view){setView(data.view);viewRef.current=data.view}setSignin(!!data.signin);
   if(!r.ok)throw new Error(data.error||'Portfolio update unavailable');setError('');setConnected(true);
  }catch(e){setError(e instanceof Error?e.message:'Connection unavailable');setConnected(false)}finally{inFlight.current=false;setBusy(false)}
 },[]);
 useEffect(()=>{const first=setTimeout(()=>void update('tick'),0),poll=setInterval(()=>void update('tick'),5000),timer=setInterval(()=>setNow(Date.now()),1000);return()=>{clearTimeout(first);clearInterval(poll);clearInterval(timer)}},[update]);
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,opts:unknown)=>void}}).modelContext;if(!context?.registerTool)return;
  const lifecycle=new AbortController();try{context.registerTool({name:'read_simulated_portfolio',title:'Read virtual portfolio',description:'Read saved virtual trading results and current positions. Does not place orders.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');const v=viewRef.current;return v?{mode:'simulation',...v}:{available:false,message:'Portfolio has not loaded.'}}},{signal:lifecycle.signal})}catch{/* Optional browser capability. */}return()=>lifecycle.abort();
 },[]);
 const agent=s.agents?.find(a=>a.id===selectedAgent);const selected=strategyInfo(agent?.state.selectedStrategy??s.selectedStrategy),fresh=connected&&!!view&&now-view.generatedAt<12000,stats=view?.stats;
 function exportTrades(){const rows=[['time_IST','side','symbol','strategy','quantity','fill_USD','fee_USD','reason','net_USD'],...s.trades.map(t=>[date(t.time),t.side,t.symbol,strategyName(t.strategy),t.quantity,t.price,t.fee,t.reason,t.net??''])];const csv=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n'),u=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),a=document.createElement('a');a.href=u;a.download='prashantverse-trades.csv';a.click();URL.revokeObjectURL(u)}
 return <main className="shell compact-desk future-desk">
  <header><div className="brand"><span className="logo">P</span>PrashantVerse<span className="tag">TRADING ACCOUNT</span></div><div className="header-meta"><span className={fresh?'positive':'amber'}><Radio size={14}/>{fresh?'Updates connected':'Updates unavailable'}</span><span className="muted">{now?clock(now):'—'} IST</span></div></header>
  <section className="desk-toolbar"><div><h1>Trading command centre</h1><p className="muted">{view?.status??'Connecting portfolio'} · Five roles · One shared decision</p></div><div className="actions">{signin?<a className="login" href="/signin-with-chatgpt?return_to=/" target="_top">Open portfolio</a>:<><Button className={s.running?'secondary':'primary'} disabled={busy||!view||s.halted||(!fresh&&!s.running)} onClick={()=>void update(s.running?'pause':'start')}>{s.running?<Pause size={15}/>:<Play size={15}/>} {s.running?'Pause entries':s.lossReview?.paused?'Resume after review':s.startedAt?'Resume bot':'Start bot'}</Button><Button variant="outline" className="secondary" disabled={busy||!fresh||(!s.positions.length&&!s.legacy?.positions.length)} onClick={()=>void update('close')}><Square size={13}/>Close positions</Button></>}</div></section>
  {error&&<div className="error" role="alert">{error}</div>}
  {s.lossReview?.paused&&<div className="notice" role="status"><b>Loss-pattern pause</b><p>{s.lossReview.losses} of the latest five closed trades lost money; combined net {money(s.lossReview.net??0)}. New entries are paused. Open stops, targets and daily exits remain monitored while this page is open. Review the journal before choosing Resume after review.</p></div>}
  <nav className="desk-tabs" aria-label="Trading views">{([['live','Live desk'],['pnl','Live P/L'],['journal','Trade journal'],['research','Research'],['core','Market core'],['settings','Settings']] as const).map(([id,label])=><Button key={id} variant="outline" className={page===id?'desk-tab active':'desk-tab'} aria-pressed={page===id} onClick={()=>setPage(id)}>{id==='settings'&&<Settings2 size={14}/>} {label}</Button>)}</nav>
  {!view&&<section className="panel"><h2>{signin?'Open your private portfolio':'Loading your portfolio'}</h2><p className="muted">Balances and trades appear after the account loads. Crypto markets run 24/7; forex setup is pending.</p></section>}
  {page==='live'&&view&&stats&&<>
   <section className="desk-metrics home-metrics"><article><span>Equity</span><strong>{money(stats.equity)}</strong></article><article><span>Today’s net P&amp;L</span><strong className={stats.dailyPnl<0?'negative':'positive'}>{signed(stats.dailyPnl)}</strong></article><article><span>Total net P&amp;L</span><strong className={stats.totalPnl<0?'negative':'positive'}>{signed(stats.totalPnl)}</strong></article><article><span>Open positions</span><strong>{view.positions.length} <small>/ 10</small></strong></article><article><span>Daily loss remaining</span><strong>{money(stats.remainingLoss)}</strong></article><article><span>Win % · after fees</span><strong>{stats.winRate===null?'Pending':stats.winRate.toFixed(1)+'%'}</strong><small>{stats.wins} wins / {stats.closed} closed trades</small></article></section>
   <TeamPanel state={s} fresh={fresh}/>
   <section className="panel desk-positions"><div className="section-top"><h2>Open trades <span className="count">{view.positions.length}</span></h2><span className="muted">Net includes entry fee</span></div><Table><TableHeader><TableRow>{['Asset','Entry','Latest price','Stop','Target','Open P&L'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{view.positions.map(p=><TableRow key={p.id}><TableCell><b> {p.symbol}/USD · {p.direction==='short'?'SHORT':'LONG'}</b><small className="block">{p.pendingExit?'Exit pending':strategyName(p.strategy)}</small></TableCell><TableCell>{price(p.entry)}</TableCell><TableCell>{price(p.mark)}{!fresh&&<small className="block amber">Last saved mark</small>}</TableCell><TableCell>{price(p.stop??null)}</TableCell><TableCell>{price(p.target??null)}</TableCell><TableCell className={p.net<0?'negative':'positive'}>{signed(p.net)}</TableCell></TableRow>)}{!view.positions.length&&<TableRow><TableCell colSpan={6} className="empty-row">No open trades · {view.status}</TableCell></TableRow>}</TableBody></Table></section>
   <SectorPanel/>

   <section className="panel"><div className="section-top"><h2>Latest completed trades</h2><Button className="secondary" onClick={()=>setPage('journal')}>View journal</Button></div><Table><TableHeader><TableRow>{['Time · IST','Asset','Exit price','Reason','Net result'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{view.recentTrades.filter(t=>(t.side==='SELL'||t.side==='COVER')).slice(0,5).map(t=><TableRow key={t.id}><TableCell>{date(t.time)}</TableCell><TableCell><b>{t.symbol}</b></TableCell><TableCell>{price(t.price)}</TableCell><TableCell>{t.reason}</TableCell><TableCell className={(t.net??0)<0?'negative':'positive'}>{signed(t.net??0)}</TableCell></TableRow>)}{!view.recentTrades.some(t=>(t.side==='SELL'||t.side==='COVER'))&&<TableRow><TableCell colSpan={5} className="empty-row">No completed trades in the recent journal.</TableCell></TableRow>}</TableBody></Table></section>
  </>}
  {page==='core'&&view&&<><DailyStatus state={s} view={view} fresh={fresh}/><TradeScene state={s} view={view} fresh={fresh}/></> }
  {page==='pnl'&&view&&stats&&<>
   <section className="panel"><div className="section-top"><h2>Live trading P/L</h2><span className={fresh?'positive':'amber'} role="status">{fresh?'Updates connected':'Last saved values'} · {clock(view.generatedAt)} IST</span></div><p className="muted">Open trades refresh about every 5 seconds while this page is open.</p></section>
   <section className="desk-metrics"><article><span>Open P/L</span><strong className={stats.unrealized<0?'negative':'positive'}>{signed(stats.unrealized)}</strong></article><article><span>Today’s P/L</span><strong className={stats.dailyPnl<0?'negative':'positive'}>{signed(stats.dailyPnl)}</strong></article><article><span>Closed P/L · all time</span><strong className={stats.realized<0?'negative':'positive'}>{signed(stats.realized)}</strong></article><article><span>Total P/L</span><strong className={stats.totalPnl<0?'negative':'positive'}>{signed(stats.totalPnl)}</strong></article><article><span>Equity</span><strong>{money(stats.equity)}</strong></article></section>
   <section className="panel"><h2>Open trade status</h2><Table><TableHeader><TableRow>{['Asset / direction','Entry','Latest price','Open P/L','Return','Status'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{view.positions.map(p=>{
    const market=view.markets.find(m=>m.symbol===p.symbol),current=fresh&&!!market?.quoteFresh,status=p.pendingExit?'Exit pending':!current?'Stale price':p.net>0?'In profit':p.net<0?'In loss':'Flat';
    return <TableRow key={p.id}><TableCell><b>{p.symbol}/USD</b><small className="block">{p.direction==='short'?'SHORT':'LONG'}</small></TableCell><TableCell>{price(p.entry)}</TableCell><TableCell>{price(p.mark)}<small className={current?'block':'block amber'}>{current?'Updated':'Last saved mark'}{market?.quoteAt?' · '+clock(market.quoteAt)+' IST':''}</small></TableCell><TableCell className={p.net<0?'negative':'positive'}>{signed(p.net)}</TableCell><TableCell className={p.net<0?'negative':'positive'}>{(p.net/(p.entry*p.quantity)*100).toFixed(2)}%</TableCell><TableCell className={!current||p.pendingExit?'amber':p.net<0?'negative':'positive'}>{status}<small className="block">{p.profitLocked?'1.5R protected stop active':'Initial stop active'}</small></TableCell></TableRow>
   })}{!view.positions.length&&<TableRow><TableCell colSpan={6} className="empty-row">No open trades. Closed results remain visible above.</TableCell></TableRow>}</TableBody></Table><p className="fine">Open P/L includes the entry fee. Exit fees and exit slippage are applied when a trade closes. Returns use each trade’s entry allocation. Stale prices do not show a live profit or loss status. Execution is simulated.</p></section>
  </>}
  {page==='journal'&&view&&stats&&<>   <section className="panel"><div className="section-top"><h2>Prices &amp; signals</h2><span className="muted">USD · Entry previews include slippage</span></div><Table><TableHeader><TableRow>{['Market','Live price','Signal','Entry price','Stop / target','Status'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{(agent?dashboardView(agent.state,view.generatedAt).markets:view.markets).map(m=>{const stale=!fresh||!m.quoteFresh;return <TableRow key={m.symbol}><TableCell><b>{m.symbol}/USD</b><small className="block">{m.name}</small></TableCell><TableCell>{price(m.price)}<small className={stale?'block amber':'block'}>{m.quoteAt?`${clock(m.quoteAt)} IST${stale?' · stale':''}`:'Awaiting quote'}</small></TableCell><TableCell><span className={'signal-badge '+(fresh?m.decision.toLowerCase():'stale')}>{fresh?(m.decision==='SIGNAL'?(m.plan?.direction==='short'?'SHORT':'BUY'):m.decision):'STALE'}</span></TableCell><TableCell>{price(fresh?m.plan?.entry??null:null)}{fresh&&m.plan&&<small className="block">{m.signalAt?clock(m.signalAt)+' IST candle':''}</small>}</TableCell><TableCell>{fresh&&m.plan?<><span className="negative">{price(m.plan.stop)}</span><small className="block positive">{price(m.plan.target)}</small></>:'—'}</TableCell><TableCell className="decision-cell">{fresh?m.reason:'Waiting for fresh update'}<details className="row-details"><summary>Details</summary><p>{m.strategy}<br/>{m.source}<br/>{m.reason}</p></details></TableCell></TableRow>})}</TableBody></Table><p className="fine">BUY / SHORT is a qualified setup, not a filled order. Position limits, cooldowns and risk checks still apply. Setups and prices refresh about every 5 seconds; signal windows expire. Forex is not connected.</p></section>
<section className="panel"><div className="section-top"><h2>Trade journal</h2><Button variant="outline" className="secondary" disabled={!s.trades.length} onClick={exportTrades}><Download size={14}/>Export CSV</Button></div><div className="journal-summary"><span>{stats.closed} closed trades</span><span>{stats.winRate===null?'Win rate pending':stats.winRate.toFixed(1)+'% wins after costs'}</span><span>{money(stats.fees)} total fees</span></div><Table><TableHeader><TableRow>{['Time · IST','Action','Asset','Fill','Fee','Reason','Net result'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{view.recentTrades.map(t=><TableRow key={t.id}><TableCell>{date(t.time)}</TableCell><TableCell className={t.side==='BUY'?'positive':'amber'}>{t.side==='SELL'?'SELL · close long':t.side==='COVER'?'COVER · close short':t.side}</TableCell><TableCell><b>{t.symbol}</b><small className="block">{t.id.startsWith('team-')?'Team':t.id.split('-').slice(0,2).join(' ')}</small><small className="block">{strategyName(t.strategy)}</small></TableCell><TableCell>{price(t.price)}</TableCell><TableCell>{money(t.fee)}</TableCell><TableCell>{t.reason}</TableCell><TableCell className={(t.net??0)<0?'negative':'positive'}>{t.net===null?'—':signed(t.net)}</TableCell></TableRow>)}{!view.recentTrades.length&&<TableRow><TableCell colSpan={7} className="empty-row">No trades recorded yet.</TableCell></TableRow>}</TableBody></Table><p className="fine">Latest 30 fills shown. CSV includes the retained journal. Historical fees and results remain unchanged.</p></section></>}
  {page==='journal'&&<LearningReview state={s} busy={busy} onReview={(key,note)=>void update('review',undefined,undefined,key,note)}/> }
  {page==='journal'&&s.legacy&&<details className="panel"><summary>Previous account archive · {s.legacy.trades.length} retained fills</summary><p>Historical cash {money(s.legacy.cash)} · Realized P/L {signed(s.legacy.realized)} · {s.legacy.positions.length} open positions. This account is paused and excluded from the new allocation.</p>{s.legacy.trades.slice(-30).reverse().map(t=><p key={t.id}>{date(t.time)} · {t.side} {t.symbol} · {price(t.price)} · {t.net===null?'Open fill':signed(t.net)}</p>)}</details>}
  {page==='journal'&&s.team?.archive&&<details className="panel"><summary>Previous ten-agent archive</summary><p>Original per-agent balances and fills retained from the rebuild. Current positions continue under their saved stops and targets.</p>{s.team.archive.agents?.map(a=><details key={a.id}><summary>{a.name} · {strategyInfo(a.state.selectedStrategy).name} · {a.state.trades.length} retained fills</summary>{a.state.trades.slice(-30).reverse().map(t=><p key={t.id}>{date(t.time)} · {t.side} {t.symbol} · {price(t.price)} · {t.net===null?'Entry fill':signed(t.net)}</p>)}</details>)}</details>}
  {page==='research'  &&<Research view={view} fresh={fresh}/>}
  {page==='settings'&&<>

   <section className="panel"><h2>Research strategy library</h2><p className="muted">Research scans these presets. Charts, News and Risk must independently approve the selected candidate before Trader can enter.</p><div className="strategy-grid">{STRATEGIES.map(config=><article className="strategy-option" key={config.id}><h3>{config.name}</h3><p>{config.interval/60000}-minute candles · {config.minBars} required</p><details><summary>Implementation rules</summary><ol>{config.rules.map(rule=><li key={rule}>{rule}</li>)}</ol></details></article>)}</div></section>
   <section className="panel"><h2>Risk &amp; execution</h2><div className="result-row"><div><span>Starting capital</span><strong>$100,000 USD · One team account</strong></div><div><span>Daily loss trigger</span><strong>$100 shared · 0.1%</strong></div><div><span>Position allocation</span><strong>$1,000 maximum · Max 10 positions</strong></div><div><span>Buy + sell fees</span><strong>$0 total</strong></div></div><details className="settings-details"><summary>Daily session and cost rules</summary><p>Long and short positions stay open until their stop or target is reached, unless manually closed or the daily loss trigger requires an exit. Short rules mirror the listed bullish rules (falling EMAs, bearish confirmation and mirrored RSI bands). Stop distances 0.4–1.5%. New crypto entries require fresh BTC and asset 1-hour trend confirmation, matching crypto news for longs, 10% above-average entry volume, and a spread no wider than 0.10%. Stops use the wider of strategy structure and 1.5×15-minute ATR14; trades exceeding the 1.5% stop ceiling wait. PENGU and TRUMP are excluded; scanner pairs must report at least $1 million 24-hour USD volume. All four roles retain a veto. New entries pause when at least three of the latest five closes lose and their combined net result is negative. Manual review and resume are required; the next day does not clear this pause. This guard tracks outcomes and does not predict winning trades. At 1.5R, hold the position, move its stop to protect 1.5R and keep existing targets; new macro-filtered crypto trades target 3R. A later reversal to the protected stop exits the trade. Repeated-loss quarantines block new entries in the same strategy, asset or exact setup until a written review is saved. Resuming the bot does not clear them. Maximum two crypto positions in the same direction; this is a conservative concentration cap, not measured correlation. No four-hour, midnight or gold pre-break exits. Gold positions wait through market closures for a fresh tradable price. Daily risk accounting resets on the next IST day without closing positions. Entries can continue across midnight; wait 30 minutes after each asset exits. Manual Pause or Close disarms continuous entries.</p><p>Trading fees are $0 for new entries and exits. Historical fees remain recorded. Adverse slippage of 0.05% each side still applies. Taxes, venue spreads, borrowing / funding and liquidity costs are excluded. Shorts are simulated with $1,000 collateral each; no leveraged or broker short order is sent. The daily loss trigger is not a guaranteed maximum loss; feed outages and gaps can delay exits.</p></details></section>
   <section className="panel"><h2>Monitoring &amp; global markets</h2><p>Strategy, signal-price and P&amp;L calculations run on the server. This page displays their saved results and triggers refreshes while open. An independent always-on execution service is not connected.</p><p>Crypto is available 24/7. Forex setup targets: {FOREX_PAIRS.join(', ')}. Forex and gold have weekday sessions; their weekend closures apply.</p><a href="/continuous-setup.md" target="_blank" rel="noreferrer">Connection and server setup</a><details className="settings-details"><summary>Gold feed and strategy</summary><p>Gold uses live Gold-API sampled candles, with no invented history or volume. Default gold strategy is EMA 9/15 when crypto uses volume-dependent V2. Warm-up requires complete observed candles. Its modelled hours follow Sunday–Friday 18:05–16:59 New York, with close attempts from 16:55.</p></details></section>
   <details className="panel settings-details"><summary>Historical strategy evaluation</summary><p>Historical long-only V2 replay: {evaluation.lastThreeDays.closed} closed trades, {evaluation.lastThreeDays.winRate?.toFixed(1)}% wins, {signed(evaluation.lastThreeDays.net)} after assumed costs. V2 failed the profitability and 60% targets. Added strategies, shorts and gold have no validated historical results.</p><a href="/strategy-evaluation.json" target="_blank" rel="noreferrer">Evaluation assumptions</a></details>
  </>}
  <footer><span>Trading account · Simulated execution</span><span>Server calculations · Monitoring requires page open</span></footer>
 </main>
}
