'use client';
import {useState} from 'react';
import type {State} from '@/lib/paper-engine';
import {performanceView} from '@/lib/trade-learning';
import {Button} from '@/components/ui/button';
const usd=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
export default function LearningReview({state,busy,onReview}:{state:State;busy:boolean;onReview:(key:string,note:string)=>void}){
 const [kind,setKind]=useState('strategy');const [key,setKey]=useState(''),[note,setNote]=useState('');const l=state.learning,blocked=Object.entries(l?.scopes??{}).filter(([,v])=>v.blocked),selected=blocked.some(([k])=>k===key)?key:'';
 return <section className="panel"><div className="section-top"><h2>Trade review &amp; safeguards</h2><span className="amber">{blocked.length} active quarantines</span></div><p>Outcome-based feedback, not a predictive AI model. Historical results cannot guarantee future profits. Blocks affect new entries; open stops and targets stay active.</p><div className="result-row">{Object.entries(l?.cohorts??{}).map(([name,p])=>{const v=performanceView(p);return <div key={name}><span>{name} · {v.closed} closes</span><strong className={v.net<0?'negative':'positive'}>{usd(v.net)}</strong><small className="block">{v.winRate?.toFixed(1)}% wins · Avg win {v.averageWin===null?'—':usd(v.averageWin)} · Avg loss {v.averageLoss===null?'—':usd(v.averageLoss)} · Mean net {v.expectancy===null?'—':usd(v.expectancy)} · Profit factor {v.profitFactor===null?'—':v.profitFactor.toFixed(2)}</small></div>})}</div><p className="fine">Stats accumulate after costs from retained closes when this review is introduced, then from new closes. Previous agents and current-team versions are separate. Original-account archive is excluded; older deleted fills cannot be recovered. Scope history remains cumulative even if the displayed fill journal is trimmed.</p>
 <details className="settings-details"><summary>Performance by strategy, asset and setup</summary><label>Group <select aria-label="Performance group" value={kind} onChange={e=>setKind(e.target.value)}><option value="strategy">Strategy &amp; direction</option><option value="asset">Asset &amp; direction</option><option value="setup">Exact setup</option></select></label><div style={{overflowX:'auto'}}><table><thead><tr>{['Group','Closes','Win %','Net','Avg win','Avg loss','Mean net','Profit factor','Status'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{Object.values(l?.scopes??{}).filter(v=>v.kind===kind).sort((a,b)=>a.performance.net-b.performance.net).map(v=>{const p=performanceView(v.performance);return <tr key={v.label}><td>{v.label}</td><td>{p.closed}</td><td>{p.winRate?.toFixed(1)}%</td><td>{usd(p.net)}</td><td>{p.averageWin===null?'—':usd(p.averageWin)}</td><td>{p.averageLoss===null?'—':usd(p.averageLoss)}</td><td>{p.expectancy===null?'—':usd(p.expectancy)}</td><td>{p.profitFactor===null?'—':p.profitFactor.toFixed(2)}</td><td>{v.blocked?'Quarantined':'Monitoring'}</td></tr>})}</tbody></table></div><p className="fine">Groups combine retained historical outcomes for review; they are not a validated prediction or automatic profit ranking.</p></details>
 <details className="settings-details"><summary>Why entries are blocked · {blocked.length}</summary>{blocked.map(([k,v])=><p key={k}><b>{v.label}</b> · {v.reason}</p>)}{!blocked.length&&<p>No active repeated-loss quarantine.</p>}<p>Strategy/direction and asset/direction: at least 3 losses among the latest 5 closes with negative combined net. Exact strategy/asset/direction: 3 consecutive losses. These are conservative review thresholds, not validated profitability thresholds.</p></details>
 {blocked.length>0&&<form onSubmit={e=>{e.preventDefault();if(selected&&note.trim().length>=12)onReview(selected,note)}}><label className="block">Review a blocked setup<select aria-label="Blocked setup" value={selected} onChange={e=>setKey(e.target.value)} required><option value="">Select quarantine</option>{blocked.map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select></label><label className="block">What did you review or change?<textarea aria-label="Review notes" value={note} onChange={e=>setNote(e.target.value)} minLength={12} maxLength={500} required placeholder="Describe the evidence and the next test before re-enabling."/></label><Button disabled={busy||!selected||note.trim().length<12}>Save review &amp; re-enable this scope</Button><p className="fine">Other overlapping blocks remain. Saving pauses new entries; Resume is still required. New losses can quarantine this scope again.</p></form>}
 <details className="settings-details"><summary>Recent review events</summary>{l?.events.slice(-20).reverse().map((e,i)=><p key={i}>{new Date(e.time).toLocaleString()} · {l.scopes[e.key]?.label} · {e.event}</p>)}</details><details className="settings-details"><summary>Entry and exit evidence · latest audited fills</summary>{state.trades.filter(t=>t.entryAudit||t.exitAudit).slice(-10).reverse().map(t=><details key={t.id}><summary>{t.symbol} · {t.side} · {t.reason}</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify({entry:t.entryAudit,exit:t.exitAudit},null,2)}</pre></details>)}</details>
 </section>;
}
