'use client';
import {useEffect,useState} from 'react';
import ValueResearch from './value-research';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {MARKETS} from '@/lib/market-config';
import {companyUrl,parseResearchCsv,type CryptoStats} from '@/lib/research';
import type {DashboardView} from '@/lib/dashboard-view';
type Feed={universe?:import('@/lib/crypto-universe').CryptoUniverse;markets:{symbol:string;stats:CryptoStats|null;error:string|null}[];generatedAt:number};
const usd=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:n<1?6:2}).format(n);
const number=(n:number)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(n);
export default function Research({view,fresh}:{view:DashboardView|null;fresh:boolean}){
 const [data,setData]=useState<Feed|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now()),[search,setSearch]=useState(''),[signal,setSignal]=useState('all'),[sort,setSort]=useState('movement'),[minMove,setMinMove]=useState(''),[symbol,setSymbol]=useState(''),[csv,setCsv]=useState<ReturnType<typeof parseResearchCsv>|null>(null),[fileName,setFileName]=useState(''),[csvError,setCsvError]=useState(''),[companySearch,setCompanySearch]=useState(''),[metric,setMetric]=useState('none'),[minimum,setMinimum]=useState(''),[maximum,setMaximum]=useState(''),[importedAt,setImportedAt]=useState<number|null>(null);
 useEffect(()=>{let alive=true,active=false;async function refresh(){if(active)return;active=true;setBusy(true);try{const r=await fetch('/api/research',{cache:'no-store'}),d=await r.json() as Feed & {error?:string};if(!r.ok)throw new Error(d.error||'Research unavailable');if(alive){setData(d);setError('')}}catch(e){if(alive)setError(e instanceof Error?e.message:'Research unavailable')}finally{active=false;if(alive)setBusy(false)}}void refresh();const id=setInterval(()=>{setNow(Date.now());void refresh()},60000);return()=>{alive=false;clearInterval(id)}},[]);
 const coins=(data?.universe?.pairs.map(p=>({symbol:p.symbol,name:p.name,icon:p.symbol.slice(0,1),color:'#77b6ff'}))??view?.markets??MARKETS).filter(m=>m.symbol!=='XAU').map(m=>{const feed=data?.markets.find(x=>x.symbol===m.symbol),market=view?.markets.find(x=>x.symbol===m.symbol),current=!error&&!!feed?.stats&&!feed.error&&now-feed.stats.fetchedAt<120000,call=fresh&&market?.quoteFresh&&market.decision==='SIGNAL'&&market.plan?(market.plan.direction==='short'?'SHORT':'BUY'):'WAIT';return {...m,feed,current,market,call}}).filter(m=>(m.symbol+' '+m.name).toLowerCase().includes(search.toLowerCase())&&(signal==='all'||m.call===signal)&&(minMove===''||m.current&&Math.abs(m.feed!.stats!.change)>=Number(minMove))).sort((a,b)=>{const value=(x:typeof a)=>!x.current?-Infinity:sort==='volume'?(x.feed!.stats!.relativeVolume??-Infinity):Math.abs(x.feed!.stats!.change);return value(b)-value(a)});
 const metricIndex=csv?.headers.indexOf(metric)??-1,rows=csv?.rows.filter(r=>r.join(' ').toLowerCase().includes(companySearch.toLowerCase())&&(metricIndex<0||minimum===''||r[metricIndex].trim()!==''&&Number.isFinite(Number(r[metricIndex].replaceAll(',','').replace('%','')))&&Number(r[metricIndex].replaceAll(',','').replace('%',''))>=Number(minimum))&&(metricIndex<0||maximum===''||r[metricIndex].trim()!==''&&Number.isFinite(Number(r[metricIndex].replaceAll(',','').replace('%','')))&&Number(r[metricIndex].replaceAll(',','').replace('%',''))<=Number(maximum)))??[];
 return <Tabs defaultValue="crypto" className="research"><TabsList><TabsTrigger value="crypto">Crypto screener</TabsTrigger><TabsTrigger value="india">Indian fundamentals</TabsTrigger></TabsList>
 <TabsContent value="crypto"><section className="panel"><div className="section-top"><h2>Crypto research screener</h2><span className="muted">{busy?'Refreshing stats…':'Coinbase Exchange · 60-second refresh'}</span></div>{error&&<p role="alert" className="amber">{error} · Previous stats are marked stale.</p>}<div className="research-controls"><label>Find coin<Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="BTC, Ethereum…"/></label><label>Setup<Select value={signal} onValueChange={setSignal}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['all','BUY','SHORT','WAIT'].map(x=><SelectItem key={x} value={x}>{x==='all'?'All setups':x}</SelectItem>)}</SelectContent></Select></label><label>Minimum |24h move| %<Input type="number" min="0" value={minMove} onChange={e=>setMinMove(e.target.value)}/></label><label>Sort<Select value={sort} onValueChange={setSort}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="movement">Largest absolute move</SelectItem><SelectItem value="volume">Relative daily volume</SelectItem></SelectContent></Select></label></div>
 <Table><TableHeader><TableRow>{['Coin','Exchange price','24h change','24h range','24h volume','Relative volume','Setup / entry / stop / target'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{coins.map(m=>{const d=m.feed?.stats;return <TableRow key={m.symbol}><TableCell><b>{m.symbol}/USD</b><small className="block">{m.name}</small></TableCell><TableCell>{d?usd(d.price):'—'}<small className={m.current?'block':'block amber'}>{m.current?'Updated':'Stale / unavailable'}{d?' · '+new Date(d.fetchedAt).toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata'})+' IST':''}</small></TableCell><TableCell className={(d?.change??0)<0?'negative':'positive'}>{d?d.change.toFixed(2)+'%':'—'}</TableCell><TableCell>{d?usd(d.low)+' – '+usd(d.high):'—'}</TableCell><TableCell>{d?number(d.volume)+' '+m.symbol:'—'}</TableCell><TableCell>{d?.relativeVolume!=null?d.relativeVolume.toFixed(2)+'×':'—'}</TableCell><TableCell><b className={m.call==='SHORT'?'negative':m.call==='BUY'?'positive':'muted'}>{m.call}</b>{m.call!=='WAIT'&&m.market?.plan&&<small className="block">{usd(m.market.plan.entry)} / {usd(m.market.plan.stop)} / {usd(m.market.plan.target)}</small>}<details><summary>Setup details</summary><p>{m.market?.strategy??'Portfolio loading'}<br/>{fresh?m.market?.reason:'Waiting for fresh portfolio signals'}<br/>{m.market?.signalAt?new Date(m.market.signalAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})+' IST candle':''}<br/>{m.feed?.error}</p></details></TableCell></TableRow>})}{!coins.length&&<TableRow><TableCell colSpan={7}>No coins match these filters.</TableCell></TableRow>}</TableBody></Table><p className="fine">Exchange stats cover 24 hours; volume is in coins. Relative volume compares the latest 24h volume with the 30-day daily average. Setup prices use the portfolio’s separate quote feed and selected strategy, so they may differ from exchange prices. BUY/SHORT setups still require position, cooldown and risk checks. These research filters do not change automated entries.</p></section></TabsContent>
 <TabsContent value="india"><section className="panel"><h2>Indian company fundamentals · Screener.in</h2><p>Open company financials, ratios, quarterly results, cash flows and filings on Screener.in. Import exported screen results below to compare companies here.</p><form className="research-controls" onSubmit={e=>{e.preventDefault();const url=companyUrl(symbol);if(url)window.open(url,'_blank','noopener,noreferrer')}}><label>NSE symbol<Input value={symbol} onChange={e=>setSymbol(e.target.value)} placeholder="RELIANCE or TCS" pattern="[A-Za-z0-9&_.-]{1,30}" required/></label><Button className="secondary" type="submit">Open company research</Button><a href="https://www.screener.in/" target="_blank" rel="noreferrer">Browse Screener.in</a></form><p className="fine">External research links only; an official live fundamentals API has not been connected. Screener.in may require sign-in for exports. Indian company prices and market capitalisation retain their source currency (INR), not USD.</p></section>
 <ValueResearch csv={csv}/><section className="panel"><div className="section-top"><h2>Compare exported fundamentals</h2><a href="https://www.screener.in/docs/changelog/export-screen-results/" target="_blank" rel="noreferrer">Screener CSV export help</a></div><label>Import Screener screen CSV (up to 2 MB / 1,000 companies)<Input type="file" accept=".csv,text/csv" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>2000000)throw new Error('CSV must be smaller than 2 MB');const parsed=parseResearchCsv(await f.text());setCsv(parsed);setFileName(f.name);setImportedAt(Date.now());setMetric('none');setMinimum('');setMaximum('');setCsvError('')}catch(err){setCsvError(err instanceof Error?err.message:'Invalid CSV')}e.target.value=''}}/></label>{csvError&&<p role="alert" className="amber">{csvError}</p>}{csv?<><p className="fine">{fileName} · {csv.rows.length} companies · User-imported snapshot, not live. Import date: {importedAt?new Date(importedAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})+' IST':'—'}. Kept only in this open page; leaving Research clears it.</p><div className="research-controls"><label>Find company<Input value={companySearch} onChange={e=>setCompanySearch(e.target.value)}/></label><label>Compare metric<Select value={metric} onValueChange={setMetric}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">No metric filter</SelectItem>{csv.headers.map(h=><SelectItem key={h} value={h}>{h}</SelectItem>)}</SelectContent></Select></label><label>Minimum value<Input type="number" value={minimum} onChange={e=>setMinimum(e.target.value)} disabled={metric==='none'}/></label><label>Maximum value<Input type="number" value={maximum} onChange={e=>setMaximum(e.target.value)} disabled={metric==='none'}/></label><Button variant="outline" className="secondary" onClick={()=>{setCsv(null);setFileName('')}}>Clear import</Button></div><Table><TableHeader><TableRow>{csv.headers.map((h,i)=><TableHead key={i}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.slice(0,100).map((r,i)=><TableRow key={i}>{r.map((c,j)=><TableCell key={j}>{c||'—'}</TableCell>)}</TableRow>)}{!rows.length&&<TableRow><TableCell colSpan={csv.headers.length}>No companies match these filters.</TableCell></TableRow>}</TableBody></Table><p className="fine">Showing {Math.min(100,rows.length)} of {rows.length} matching companies. Only exported columns are available; missing ratios are not estimated. Fundamental data supports research and does not place Indian stock orders.</p></>:<p className="muted">No fundamentals imported. Export a screen as CSV from your Screener.in account, then select that file here. Look for P/E, ROCE, ROE, debt and growth columns in your export.</p>}</section></TabsContent></Tabs>
}
