
'use client';
import {useEffect,useState} from 'react';
import type {SectorBoard} from '@/lib/sector-news';
const date=(n:number)=>new Date(n).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});
export default function SectorPanel(){
 const [board,setBoard]=useState<SectorBoard|null>(null),[error,setError]=useState(''),[now,setNow]=useState(0);
 useEffect(()=>{const abort=new AbortController();let busy=false;const refresh=async()=>{if(busy)return;busy=true;try{const r=await fetch('/api/sector-news',{signal:abort.signal});if(!r.ok||!r.headers.get('content-type')?.includes('application/json'))throw new Error('Sector news unavailable');setBoard(await r.json());setError('')}catch(e){if(!abort.signal.aborted)setError(e instanceof Error?e.message:'Sector news unavailable')}finally{busy=false}};void refresh();const poll=setInterval(()=>void refresh(),60000),timer=setInterval(()=>setNow(Date.now()),5000);return()=>{abort.abort();clearInterval(poll);clearInterval(timer)}},[]);
 const stale=!!error||!board||now-board.generatedAt>5*60000;
 return <section className="panel sector-panel" aria-label="Global sector news and research signals"><div className="section-top"><div><span className="sector-eyebrow">GLOBAL NEWS / RESEARCH WATCH</span><h2>Where the market is moving</h2></div><span className="muted">{board?'Checked '+date(board.generatedAt)+' IST':'Connecting news feeds'}</span></div><p className="sector-intro">Green: buy watch · Red: short watch · Grey: neutral. Headline direction, not a confirmed entry or long-term valuation.</p>
 {error&&<p className="amber" role="status">{error} · Directional signals paused.</p>}
 {!board&&!error&&<p className="muted">Loading global sector headlines…</p>}
 {board&&<><div className="sector-grid">{board.sectors.map(s=>{const tone=stale?'neutral':s.tone;return <article className={'sector-card '+tone} key={s.id}><div className="sector-card-top"><h3>{s.name}</h3><span className={'sector-label '+tone}>{tone==='buy'?'BUY WATCH':tone==='short'?'SHORT WATCH':'NEUTRAL'}</span></div><p>{stale?'Waiting for fresh news':s.reason}</p>{s.headlines[0]&&<a className="sector-lead" href={s.headlines[0].url} target="_blank" rel="noopener noreferrer">{s.headlines[0].title}</a>}{s.headlines.length?<details><summary>{s.headlines.length} headline{s.headlines.length>1?'s':''} · {date(s.headlines[0].publishedAt)} IST</summary>{s.headlines.map(h=><div className="sector-headline" key={h.url}><a href={h.url} target="_blank" rel="noopener noreferrer">{h.title}</a><small>{h.source} · {date(h.publishedAt)} IST</small></div>)}</details>:<small>Awaiting relevant headlines</small>}</article>})}</div><details className="sector-method"><summary>Sources and signal method</summary><p>Updates every minute while this page is open. Uses dated headlines from the last 24 hours. Explicit sector mentions and unambiguous rise/fall language determine the colour; mixed, speculative or cross-sector headlines stay neutral. Coverage is limited and wording can be misclassified. No price confirmation, investment valuation or automatic order is implied. Global stock sectors are research-only; crypto and gold orders still require the trading team’s independent checks.</p>{board.sources.map(s=><p key={s.name}>{s.name} · {s.fetchedAt?date(s.fetchedAt)+' IST':'Not connected'}{s.error?' · '+s.error:''}</p>)}</details></>}
 </section>
}
