'use client';
import {useEffect,useState,type CSSProperties} from 'react';
import {Search,Newspaper,TrendingUp,ShieldCheck,Bot,Pause,Play,Radio} from 'lucide-react';
import type {State} from '@/lib/paper-engine';
import type {Vote} from '@/lib/decision-team';
const roles=[{role:'Research',icon:Search,color:'#62e6ed',job:'Scan 50 liquid USD pairs'},{role:'News',icon:Newspaper,color:'#c7a2ff',job:'Review event risk'},{role:'Charts',icon:TrendingUp,color:'#79b9ff',job:'Confirm price action'},{role:'Risk',icon:ShieldCheck,color:'#ffcd7d',job:'Protect the account'},{role:'Trader',icon:Bot,color:'#8ce5b3',job:'Execute the agreement'}] as const;
export default function TeamDiscussion({state:s,fresh}:{state:State;fresh:boolean}){
 const team=s.team!,[active,setActive]=useState(0),[motion,setMotion]=useState(true),[reduced,setReduced]=useState(false);
 useEffect(()=>{const q=window.matchMedia('(prefers-reduced-motion: reduce)'),sync=()=>setReduced(q.matches);sync();q.addEventListener('change',sync);return()=>q.removeEventListener('change',sync)},[]);
 useEffect(()=>{if(!fresh||!motion||reduced)return;setActive(0);const timers=[1,2,3,4].map(i=>setTimeout(()=>setActive(i),i*650));return()=>timers.forEach(clearTimeout)},[team.checkedAt,fresh,motion,reduced]);
 const votes:Vote[]=roles.map(r=>team.votes.find(v=>v.role===r.role)??{role:r.role,status:'WAIT',reason:'Waiting for the first team scan'}),current=roles[active],vote=votes[active],Icon=current.icon,agreed=votes.slice(0,4).filter(v=>v.status==='PASS').length,animated=fresh&&motion&&!reduced&&!!team.checkedAt;
 return <div className={'discussion-room '+(animated?'is-animated':'motion-off')}>
  <div className="discussion-toolbar"><div><span className="discussion-eyebrow">PRASHANTVERSE / TEAM ROOM</span><h2>Five minds. One decision.</h2></div><div className="discussion-controls"><span className={fresh?'positive':'amber'}><Radio size={13}/>{fresh?'Updates connected':'Saved snapshot'}</span><button type="button" aria-pressed={!motion} aria-label={motion?'Pause discussion animation':'Resume discussion animation'} onClick={()=>setMotion(v=>!v)}>{motion?<Pause size={14}/>:<Play size={14}/>}</button></div></div>
  <div className="discussion-flow">{roles.map((r,i)=>{const AgentIcon=r.icon,v=votes[i];return <article key={r.role} style={{'--agent-color':r.color} as CSSProperties} className={'discussion-agent '+(animated&&active===i?'speaking ':'')+(v.status==='BLOCK'?'veto':'')}><div className="agent-avatar"><AgentIcon size={25}/><span className="avatar-ping"/></div><div className="agent-identity"><span>AGENT 0{i+1}</span><h3>{r.role}</h3><small>{r.job}</small></div><div className={'discussion-verdict '+(!fresh?'stale':v.status.toLowerCase())}>{!fresh?'STALE':v.status==='PASS'?'AGREES':v.status==='BLOCK'?'VETO':'WAITING'}<span className="voice-bars"><i/><i/><i/><i/></span></div><p>{v.reason}</p><div className="agent-channel"><i/>{animated&&active===i?'Reviewing this check':'Check recorded'}</div></article>})}</div>
  <div className="discussion-conversation" style={{'--agent-color':current.color} as CSSProperties}><div className="conversation-avatar"><Icon size={21}/></div><div className="conversation-message"><span>{current.role} <small>· Decision replay</small></span><p>{vote.reason}</p></div><div className="conversation-stamp">{team.checkedAt?new Date(team.checkedAt).toLocaleTimeString():'Not scanned'}<small>Latest server check</small></div></div>
  <div className="discussion-consensus"><div><span className="discussion-eyebrow">SHARED DECISION</span><h3>{fresh?team.decision:'Saved decision · refresh pending'}</h3></div><div className="consensus-meter"><div><b>{agreed} / 4</b><span>required checks agree</span></div><div className="consensus-segments">{votes.slice(0,4).map(v=><i key={v.role} className={fresh?v.status.toLowerCase():'stale'} title={`${v.role}: ${v.status}`}/>)}</div><small>{s.positions.length} / 10 positions · $100 daily trigger</small></div></div>
  <p className="discussion-disclosure">Animation replays the actual saved checks; it is not a generated conversation. Rules-based team · Simulated execution.</p>
 </div>
}
