'use client';
import type {State} from '@/lib/paper-engine';
import {strategyInfo} from '@/lib/strategies';
import TeamDiscussion from './team-discussion';
import {entryPlan} from '@/lib/entry-plan';
const money=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v);
const descriptions={Research:'Scans ten strategy presets for fresh BUY / SHORT setups.',News:'Checks public headlines for configured event-risk flags.',Charts:'Confirms completed-candle momentum and price action.',Risk:'Sizes entries within the $100 daily trigger and $20 planned trade risk.',Trader:'Places one decision only after all required checks pass.'};
export default function TeamPanel({state:s,fresh}:{state:State;fresh:boolean}){
 const team=s.team;if(!team)return null;
 return <section className="panel team-room-panel"><TeamDiscussion state={s} fresh={fresh}/>
 {s.positions.length>5&&<p className="amber">{s.positions.length} positions remain from the previous accounts. Their saved exits continue; new team entries wait until fewer than five are open.</p>}
 <div className="universe-status"><b>Crypto scanner · {team.universe?.pairs.length??0} / 50 filtered USD pairs</b><span>{team.universe?.source??'Connecting liquidity ranking'}</span><p>{team.universe?.error??'Ranked by reported 24-hour USD volume; stablecoins, disabled markets, PENGU and TRUMP excluded; minimum $1m reported daily USD volume.'}</p><small>{team.universe?.pairs.filter(p=>team.scanUpdated?.[p.symbol]&&Date.now()-team.scanUpdated[p.symbol]<120000).length??0} pairs analysed in the last two minutes · Rotating five pairs per update. Cached screener prices never substitute for fresh execution quotes.</small></div>
 <details className="settings-details"><summary>Candidate decisions · {team.candidates.length} fresh setups</summary>{team.candidates.length?<div className="team-candidates">{team.candidates.slice(0,10).map(c=><article key={c.symbol+c.strategy}><b>{c.analysis.direction==='short'?'SHORT':'BUY'} {c.symbol} · {strategyInfo(c.strategy).name}</b><p>{s.quotes.find(q=>q.symbol===c.symbol)&&(()=>{const plan=entryPlan(s.quotes.find(q=>q.symbol===c.symbol)!.price,c.analysis);return plan?`Entry ${money(plan.entry)} · Stop ${money(plan.stop)} · Target ${money(plan.target)}`:'Entry plan unavailable'})()}</p><p>{c.approved?'Checks agree':'Waiting'} · Allocation {money(c.allocation)} · Planned risk {money(c.estimatedRisk)}</p>{c.votes.map(v=><small className="block" key={v.role}>{v.role}: {v.status} · {v.reason}</small>)}</article>)}</div>:<p>No fresh setups. The team waits rather than forcing a trade.</p>}</details>
 <details className="settings-details"><summary>News source &amp; event context</summary><p>{team.news?.source??'News pending'} · {team.news?.fetchedAt?new Date(team.news.fetchedAt).toLocaleString():'Not fetched'}{team.news?.error?' · '+team.news.error:''}</p><p className="fine">Configured keywords trigger a two-hour entry pause. Crypto uses CoinDesk; gold uses Investing.com commodities headlines. These feeds do not cover every event or predict direction. Missing/stale news blocks new entries. Gold respects its weekday sessions and observed-candle warm-up.</p>{team.news?.headlines.slice(0,6).map(h=><p key={h.url}><a href={h.url} target="_blank" rel="noreferrer">{h.title}</a><small className="block">{new Date(h.publishedAt).toLocaleString()}</small></p>)}<h3>Gold / macro headlines</h3><p>{team.macroNews?.source??'Commodities news pending'}{team.macroNews?.error?' · '+team.macroNews.error:''}</p>{team.macroNews?.headlines.slice(0,6).map(h=><p key={h.url}><a href={h.url} target="_blank" rel="noreferrer">{h.title}</a><small className="block">{new Date(h.publishedAt).toLocaleString()}</small></p>)}</details>
 </section>
}
