'use client';
import {useState} from 'react';
import {Input} from '@/components/ui/input';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {evaluateValue,VALUE_RULES} from '@/lib/value-research';
import {companyUrl} from '@/lib/research';
export default function ValueResearch({csv}:{csv:{headers:string[];rows:string[][]}|null}){
 const [asOf,setAsOf]=useState('');const results=csv?evaluateValue(csv,asOf):[],candidates=results.filter(r=>r.status==='Research candidate');
 return <section className="panel"><h2>Undervalued candidates · long-term research</h2><p>Identify profitable, growing companies trading below their industry P/E in your imported snapshot. Passing this screen suggests a company for deeper research; it does not establish fair value or a buy recommendation.</p><details className="settings-details"><summary>Screen rules and required CSV columns</summary><ul>{VALUE_RULES.map(x=><li key={x}>{x}</li>)}</ul><p>Export Name, P/E, Industry PE, ROE, ROCE, Debt to equity, Sales growth 3Years and Profit growth 3Years. Optional Sector / Industry and NSE Code columns improve classification and company links. Missing values remain unknown. These fixed thresholds are an experimental screen, not a validated investment model. Banks, insurers and financial firms need separate valuation methods; when a sector column identifies them, they are excluded.</p></details><label className="block">Fundamentals snapshot date (confirm on source)<Input type="date" value={asOf} onChange={e=>setAsOf(e.target.value)} style={{maxWidth:240,marginTop:8}}/></label><p className="fine">Use data dated within the past 31 days. Import time is not the source date. A recent snapshot can still contain older financial reporting periods.</p>
 {!csv?<p className="muted">Import a Screener CSV below to generate research candidates. No company picks are generated without data.</p>:<><p><b>{candidates.length} companies pass this screen</b> · {results.length} companies evaluated</p><Table><TableHeader><TableRow>{['Company','Research status','Checks passed','P/E discount vs industry','Evidence / next review'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{results.slice(0,50).map(r=><TableRow key={r.index}><TableCell><b>{r.name}</b><small className="block">{r.sector??'Sector not supplied; verify financial-company classification'}</small>{r.symbol&&companyUrl(r.symbol)&&<a href={companyUrl(r.symbol)!} target="_blank" rel="noreferrer">Company financials</a>}</TableCell><TableCell className={r.status==='Research candidate'?'positive':'amber'}>{r.status}</TableCell><TableCell>{r.passed} / {r.checks.length}</TableCell><TableCell>{r.discount===null?'—':r.discount.toFixed(1)+'%'}</TableCell><TableCell><details><summary>Why this result?</summary>{r.checks.map(c=><p key={c.label}>{c.label}: {c.value} · {c.known?(c.pass?'Pass':'Fail'):'Unknown'}</p>)}</details>{r.status==='Research candidate'&&<small className="block">Review audited cash flow, debt maturities, promoter pledges, governance, industry prospects and valuation against peers before buying.</small>}</TableCell></TableRow>)}{!results.length&&<TableRow><TableCell colSpan={5}>No companies in this import.</TableCell></TableRow>}</TableBody></Table><p className="fine">Shows up to 50 companies from the entire imported file, independent of comparison filters. P/E discount is a relative-multiple comparison, not expected upside. Fair-value targets, margin of safety and return forecasts are not calculated. Intraday trading rules and positions are unchanged.</p></>}
 <p className="fine"><a href="https://www.finra.org/investors/investing/investment-products/stocks/evaluating-stocks" target="_blank" rel="noreferrer">Guide to evaluating company financials and valuation</a></p></section>
}
