import {test} from 'node:test';
import assert from 'node:assert/strict';
import {ensureFleet,syncFleet,enforceFleetRisk,fleetAdvance} from './agent-fleet.ts';
import {initial,summary,type Quote} from './paper-engine.ts';
import {CRYPTO_SYMBOLS} from './market-config.ts';
const now=Date.parse('2026-10-04T10:00:00Z');const quotes:Quote[]=CRYPTO_SYMBOLS.map(symbol=>({symbol,price:100,fetchedAt:now}));
test('ten isolated 10k accounts preserve previous trades without sharing arrays',()=>{const s=initial();s.realized=123;ensureFleet(s);assert.equal(s.agents!.length,10);assert.equal(s.legacy!.realized,123);for(const a of s.agents!)assert.equal(a.state.cash,10000);s.agents![0].state.cash=9990;syncFleet(s);assert.equal(s.cash,99990);assert.equal(summary(s).totalPnl,-10);assert.equal(s.agents![1].state.cash,10000);assert.notEqual(s.agents![0].state.trades,s.agents![1].state.trades);assert.equal(new Set(s.agents!.map(a=>a.state.selectedStrategy )).size,10)});
test('combined losses lock all agents even if each is under the trigger',()=>{const s=ensureFleet(initial());for(const a of s.agents!){a.state.cash=9980;a.state.running=true}assert.equal(enforceFleetRisk(s,now),false);assert.ok(s.agents!.every(a=>a.state.halted&&!a.state.running));assert.equal(summary(s).dailyPnl,-200);const restored=JSON.parse(JSON.stringify(s));assert.equal(enforceFleetRisk(restored,now),false)});
test('individual pause leaves other agents scanning and two-position limits configured',()=>{const s=ensureFleet(initial());fleetAdvance(s,quotes,now,'start',{});fleetAdvance(s,quotes,now+1,'pause',{},'agent-2');assert.equal(s.agents![1].state.running,false);assert.equal(s.agents![0].state.running,true);assert.ok(s.agents!.every(a=>a.state.maxPositions===2&&a.state.allocation===1000));assert.equal(s.cash,100000)});
test('old open positions prevent starting a new allocation',()=>{const s=initial();s.positions.push({id:'old',symbol:'BTC',kind:'intraday',quantity:1,entry:100,mark:100,entryFee:2.5,openedAt:now});ensureFleet(s);assert.throws(()=>fleetAdvance(s,quotes,now,'start',{}),/previous account/);assert.equal(s.legacy!.positions.length,1);assert.ok(s.agents!.every(a=>!a.state.running))});
import fs from 'node:fs';
import type {Candle} from './strategy.ts';
const fixture=JSON.parse(fs.readFileSync(new URL('./fixtures/qualified-btc.json',import.meta.url),'utf8')) as Candle[];
test('qualified parallel entries use separate IDs and cannot repeat a candle after reload',()=>{let s=ensureFleet(initial());for(const a of s.agents!)a.state.selectedStrategy='trend-pullback-v2';const t=fixture.at(-1)!.time+300000,q=CRYPTO_SYMBOLS.map(symbol=>({symbol,price:fixture.at(-1)!.close,fetchedAt:t})),bars=Object.fromEntries(CRYPTO_SYMBOLS.map(symbol=>[symbol,fixture]));fleetAdvance(s,q,t,'start',{'trend-pullback-v2':bars});assert.equal(s.positions.length,20);assert.equal(new Set(s.positions.map(p=>p.id)).size,20);assert.ok(s.agents!.every(a=>a.state.positions.length===2&&Math.abs(a.state.positions[0].quantity*a.state.positions[0].entry-1000)<1e-8));s=JSON.parse(JSON.stringify(s));fleetAdvance(s,q.map(x=>({...x,fetchedAt:t+15000})),t+15000,'tick',{});assert.equal(s.trades.length,20);fleetAdvance(s,q.map(x=>({...x,fetchedAt:t+30000,price:x.price*.9})),t+30000,'tick',{});assert.equal(s.positions.length,0);assert.ok(s.halted);assert.ok(s.agents!.every(a=>!a.state.running))});

test('existing one-position accounts migrate without changing balances or trade history',()=>{const s=ensureFleet(initial());s.maxPositions=5;for(const a of s.agents!)a.state.maxPositions=1;s.agents![0].state.cash=9876;const before=JSON.stringify(s.agents![0].state.trades);ensureFleet(s);assert.equal(s.maxPositions,20);assert.ok(s.agents!.every(a=>a.state.maxPositions===2));assert.equal(s.agents![0].state.cash,9876);assert.equal(JSON.stringify(s.agents![0].state.trades),before)});

test('five-agent upgrade adds capital without erasing P/L or same-day risk lock',()=>{const s=ensureFleet(initial());s.agents=s.agents!.slice(0,5);delete s.fleetVersion;s.startingCapital=50000;s.agents[0].state.cash=9900;s.halted=true;const original=s.agents[0];ensureFleet(s);syncFleet(s);assert.equal(s.agents.length,10);assert.equal(s.agents[0],original);assert.equal(s.cash,99900);assert.equal(summary(s).totalPnl,-100);assert.equal(summary(s).dailyPnl,-100);assert.ok(s.halted);assert.ok(s.agents.slice(5).every(a=>a.state.halted&&!a.state.running));ensureFleet(s);assert.equal(s.agents.length,10);assert.equal(s.cash,99900)});

test('new shared threshold migrates existing limits and locks at $100 including saved losses',()=>{const s=ensureFleet(initial());s.dailyLimit=500;for(const a of s.agents!)a.state.dailyLimit=500;ensureFleet(s);assert.equal(s.dailyLimit,100);assert.ok(s.agents!.every(a=>a.state.dailyLimit===100));s.agents![0].state.cash=9900.01;assert.equal(enforceFleetRisk(s,now),true);s.agents![0].state.cash=9900;assert.equal(enforceFleetRisk(s,now),false)});
