import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {rankLiquidPairs} from './crypto-universe.ts';import {initial,type Quote} from './paper-engine.ts';import {ensureTeam,teamAdvance,chartCheck} from './decision-team.ts';import {analyzeStrategy} from './strategies.ts';import {dashboardView} from './dashboard-view.ts';import type {Candle} from './strategy.ts';
const now=Date.parse('2026-10-06T12:00:00Z');
const product=(symbol:string,volume=100)=>({product_id:symbol+'-USD',base_currency_id:symbol,base_name:symbol,quote_currency_id:'USD',product_type:'SPOT',status:'online',price:'100',volume_24h:'1',approximate_quote_24h_volume:String(volume)});
test('ranks 50 by USD volume with no duplicates and excludes stablecoins/disabled/other quotes',()=>{const items:Record<string,unknown>[]=Array.from({length:65},(_,i)=>product('COIN'+i,i+1));items.push(product('USDC',100000),{...product('NO',100000),trading_disabled:true},{...product('EUR',100000),quote_currency_id:'EUR'},product('COIN64',1));const u=rankLiquidPairs({products:items},now);assert.equal(u.pairs.length,50);assert.equal(u.pairs[0].symbol,'COIN64');assert.equal(new Set(u.pairs.map(p=>p.symbol)).size,50);assert.ok(!u.pairs.some(p=>['USDC','NO','EUR'].includes(p.symbol)));assert.equal(u.pairs.at(-1)!.symbol,'COIN15')});
test('invalid feed/zero-volume prices never invent a ranking',()=>{assert.throws(()=>rankLiquidPairs({},now));assert.throws(()=>rankLiquidPairs({products:[{...product('BAD'),price:'NaN'},{...product('ZERO',0),volume_24h:'0'}]},now))});
const bars=JSON.parse(fs.readFileSync(new URL('./fixtures/qualified-btc.json',import.meta.url),'utf8')) as Candle[],t=bars.at(-1)!.time+300000,price=bars.at(-1)!.close;
function state(){const s=ensureTeam(initial());s.team!.universe=rankLiquidPairs({products:[product('NEWCOIN')]},t);s.team!.news={source:'CoinDesk RSS',fetchedAt:t,headlines:[{title:'Market update',url:'https://www.coindesk.com/test',publishedAt:t}]};s.team!.research={'trend-pullback-v2':{NEWCOIN:{analysis:analyzeStrategy('trend-pullback-v2',bars,t),chart:chartCheck('trend-pullback-v2',bars,t)}}};return s}
test('new eligible dynamic pair executes only with fresh quotes and unanimous checks',()=>{const s=state(),q:Quote[]=[{symbol:'NEWCOIN',price,fetchedAt:t}];teamAdvance(s,q,t,'start');assert.equal(s.positions.length,1);assert.equal(s.positions[0].symbol,'NEWCOIN');assert.equal(dashboardView(s,t).markets.find(m=>m.symbol==='NEWCOIN')?.decision,'OPEN')});
test('failed universe vetoes entries; existing dynamic position remains monitored after leaving ranking',()=>{const s=state();teamAdvance(s,[{symbol:'NEWCOIN',price,fetchedAt:t}],t,'start');s.team!.universe={pairs:[],source:'Coinbase',fetchedAt:t,error:'Ranking unavailable'};teamAdvance(s,[{symbol:'NEWCOIN',price:price*.9,fetchedAt:t+10000}],t+10000,'tick');assert.equal(s.positions.length,0);assert.equal(s.trades.filter(t=>t.side==='BUY').length,1);assert.ok(s.trades.some(t=>t.side==='SELL'))});
