import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {initial,summary,type Quote} from './paper-engine.ts';
import {ensureFleet} from './agent-fleet.ts';
import {ensureTeam,teamAdvance,evaluateTeam,riskCheck,chartCheck} from './decision-team.ts';
import {newsGate,parseNews,type NewsSnapshot} from './team-news.ts';
import {analyzeStrategy} from './strategies.ts';
import {CRYPTO_SYMBOLS} from './market-config.ts';
import type {Candle} from './strategy.ts';
const fixture=JSON.parse(fs.readFileSync(new URL('./fixtures/qualified-btc.json',import.meta.url),'utf8')) as Candle[];
const now=fixture.at(-1)!.time+300000,price=fixture.at(-1)!.close;
const quotes=(t=now,mult=1):Quote[]=>CRYPTO_SYMBOLS.map(symbol=>({symbol,price:price*mult,fetchedAt:t}));
const news=(t=now,title='Bitcoin market update'):NewsSnapshot=>({source:'CoinDesk RSS',fetchedAt:t,headlines:[{title,url:'https://www.coindesk.com/markets/example',publishedAt:t-1000}]});
function ready(){const s=ensureTeam(initial());s.team!.news=news();s.team!.research={'trend-pullback-v2':Object.fromEntries(CRYPTO_SYMBOLS.map(symbol=>[symbol,{analysis:analyzeStrategy('trend-pullback-v2',fixture,now),chart:chartCheck('trend-pullback-v2',fixture,now)}]))};return s}
test('migration consolidates ten accounts without resetting cash, P/L, open trades or daily lock',()=>{const s=ensureFleet(initial());s.agents![0].state.cash=9900;s.agents![0].state.realized=-100;s.halted=true;const old=structuredClone(s.agents);ensureTeam(s);assert.equal(s.cash,99900);assert.equal(summary(s).totalPnl,-100);assert.equal(s.realized,-100);assert.equal(s.halted,true);assert.equal(s.running,false);assert.deepEqual(s.team!.archive!.agents,old);assert.equal(s.agents,undefined);ensureTeam(s);assert.equal(s.cash,99900)});
test('news parser validates URLs, dates and feed content; event and stale data never approve',()=>{const xml=`<rss><channel><item><title><![CDATA[Bitcoin &amp; markets]]></title><link>https://www.coindesk.com/markets/test</link><pubDate>${new Date(now).toUTCString()}</pubDate></item></channel></rss>`;const n=parseNews(xml,now);assert.equal(n.headlines.length,1);assert.equal(n.headlines[0].title,'Bitcoin & markets');assert.ok(newsGate(n,now,'BTC').approved);assert.equal(newsGate(news(now,'Exchange withdrawals suspended after hack'),now,'BTC').approved,false);assert.equal(newsGate(n,now+300001,'BTC').approved,false);assert.equal(newsGate(n,now,'XAU').approved,false);assert.equal(newsGate(undefined,now,'BTC').approved,false);assert.throws(()=>parseNews(xml.replace('https://www.coindesk.com/markets/test','javascript:alert(1)'),now));assert.throws(()=>parseNews('<html>Error</html>',now))});
test('every required role can veto; unavailable news does not affect monitoring exits',()=>{for(const block of ['news','charts','risk']){const s=ready();s.quotes=quotes();s.running=true;if(block==='news')s.team!.news=undefined;if(block==='charts')for(const c of Object.values(s.team!.research['trend-pullback-v2']!))c!.chart.approved=false;if(block==='risk')s.halted=true;evaluateTeam(s,now);assert.ok(s.team!.candidates.every(c=>!c.approved));teamAdvance(s,quotes(),now,'tick');assert.equal(s.positions.length,0)}});
test('trader requires agreement; sizes within $20 and caps same-direction crypto at two, including reload',()=>{let s=ready();teamAdvance(s,quotes(),now,'start');assert.equal(s.positions.length,1);assert.ok(s.positions[0].entryAudit);assert.equal(s.positions[0].entryAudit!.votes.length,5);assert.equal(s.positions[0].entryAudit!.plan!.stop,s.positions[0].stop);assert.ok(s.team!.votes.every(v=>v.status==='PASS'));assert.ok(s.allocation!<=1000);assert.ok(s.team!.candidates.find(c=>c.symbol===s.positions[0].symbol)!.estimatedRisk<=20);s=JSON.parse(JSON.stringify(s));teamAdvance(s,quotes(now+10000),now+10000,'tick');assert.equal(s.positions.length,2);for(const delta of [20000,30000,40000,50000])teamAdvance(s,quotes(now+delta),now+delta,'tick');assert.equal(s.positions.length,2);assert.equal(s.trades.filter(t=>t.side==='BUY'||t.side==='SHORT').length,2);assert.ok(s.team!.candidates.some(c=>c.votes.some(v=>v.reason.includes('Concentration guard'))))});
test('stale news blocks entries but stops still close positions',()=>{const s=ready();teamAdvance(s,quotes(),now,'start');s.team!.news=undefined;teamAdvance(s,quotes(now+10000,.9),now+10000,'tick');assert.equal(s.positions.length,0);assert.ok(s.trades.some(t=>t.side==='SELL'));const exit=s.trades.find(t=>t.side==='SELL')!;assert.ok(exit.entryAudit);assert.equal(exit.exitAudit?.reason,exit.reason);assert.equal(exit.exitAudit?.quoteAt,now+10000);assert.equal(s.learning!.cohorts['New safeguards'].closed,1);assert.equal(s.trades.filter(t=>t.side==='BUY').length,1)});
test('risk reserves open stop exposure and never spends the last $100 budget twice',()=>{const s=ready();s.quotes=quotes();s.cash=99900.01;assert.equal(riskCheck(s,'BTC',analyzeStrategy('trend-pullback-v2',fixture,now)).approved,false);s.cash=100000;const c=riskCheck(s,'BTC',analyzeStrategy('trend-pullback-v2',fixture,now));assert.ok(c.approved);assert.ok(c.estimatedRisk<=20)});
test('chart role rejects unfinished or gapped history and weak price action',()=>{assert.equal(chartCheck('trend-pullback-v2',fixture.slice(0,10),now).approved,false);assert.equal(chartCheck('trend-pullback-v2',fixture.filter((_,i)=>i!==60),now).approved,false);const b=structuredClone(fixture);b.at(-1)!.close=b.at(-1)!.open;assert.equal(chartCheck('trend-pullback-v2',b,now).approved,false)});

test('migration keeps excess open positions under their original exits and blocks new exposure',()=>{const s=ensureFleet(initial());for(let i=0;i<6;i++){const a=s.agents![i];a.state.cash=8999;a.state.positions=[{id:`old-${i}`,symbol:CRYPTO_SYMBOLS[i],kind:'intraday',quantity:1000/price,entry:price,mark:price,entryFee:1,openedAt:now,stop:price*.99,target:price*1.02,initialRisk:price*.01}]};ensureTeam(s);const ids=s.positions.map(p=>p.id);s.team!.news=news();teamAdvance(s,quotes(),now,'tick');assert.deepEqual(s.positions.map(p=>p.id),ids);assert.equal(s.positions.length,6);assert.equal(s.trades.length,0)});
test('gold joins research and trades only with fresh macro news and an open session',()=>{
 const t=Date.parse('2026-10-06T12:00:00Z'),bars:Candle[]=Array.from({length:120},(_,i)=>({time:t-(120-i)*300000,open:4000,close:4000,low:3990,high:4010,volume:0}));Object.assign(bars.at(-1)!,{open:4000,close:4030,low:3999,high:4035});
 const prepare=()=>{const s=ensureTeam(initial());s.gold={frames:{300000:{closed:structuredClone(bars)}}};s.team!.macroNews={source:'Investing.com commodities RSS',fetchedAt:t,headlines:[{title:'Gold market update',url:'https://www.investing.com/news/commodities-news/gold',publishedAt:t-1000}]};return s};
 const q=[...quotes(t),{symbol:'XAU' as const,price:4030,fetchedAt:t}];const s=prepare();teamAdvance(s,q,t,'start');assert.equal(s.positions.length,1);assert.equal(s.positions[0].symbol,'XAU');assert.equal(s.positions[0].strategy,'ema-9-15');assert.ok(s.team!.votes.every(v=>v.status==='PASS'));assert.equal(s.positions[0].entryFee,0);
 const missing=prepare();missing.team!.macroNews=undefined;teamAdvance(missing,q,t,'start');assert.equal(missing.positions.length,0);
 const flagged=prepare();flagged.team!.macroNews!.headlines[0].title='Fed interest rate decision';teamAdvance(flagged,q,t,'start');assert.equal(flagged.positions.length,0);
});

test('saved team limit migrates to $100 without resetting existing losses',()=>{const s=ready();s.dailyLimit=200;s.startedAt=now;s.dayBase=100000;s.cash=99900;ensureTeam(s);assert.equal(s.dailyLimit,100);assert.equal(summary(s).dailyPnl,-100);teamAdvance(s,quotes(),now,'tick');assert.equal(s.halted,true);assert.equal(s.running,false)});

test('existing team migrates from five to ten positions without changing account history',()=>{const s=ready();s.maxPositions=5;const cash=s.cash,trades=JSON.stringify(s.trades);ensureTeam(s);assert.equal(s.maxPositions,10);assert.equal(s.cash,cash);assert.equal(JSON.stringify(s.trades),trades);assert.equal(s.dailyLimit,100)});
