import {test} from 'node:test';
import assert from 'node:assert/strict';
import {initial,advance,istDay,type State} from './paper-engine.ts';
import {ensureTeam} from './decision-team.ts';
const start=Date.parse('2026-10-05T10:00:00Z');
function account(symbol='BTC'):State{const s=initial();ensureTeam(s);s.startedAt=start;s.day=istDay(start);s.cash=99900;s.positions=[{id:'carry',symbol,kind:'intraday',quantity:1,entry:100,mark:100,entryFee:1,openedAt:start,strategy:'ema-9-15',stop:90,target:120,initialRisk:10}];return s}
function tick(s:State,t:number,price=100,action='tick'){return advance(s,[{symbol:s.positions[0]?.symbol??'BTC',price,fetchedAt:t}],t,action,undefined,()=>false,true)}
test('team holds beyond four hours, midnight, reload and daily rollover',()=>{let s=account();for(const t of [start+4*3600000,Date.parse('2026-10-05T18:26:00Z'),Date.parse('2026-10-05T18:31:00Z'),start+86400000]){s=JSON.parse(JSON.stringify(s));ensureTeam(s);tick(s,t);assert.equal(s.positions.length,1);assert.equal(s.trades.length,0)}assert.equal(s.strategyMode,'price-exits');tick(s,start+86400000+5000,100,'start');assert.equal(s.running,true)});
test('carried positions still exit at target, stop and manual close',()=>{for(const [price,reason] of [[120,'2R profit target'],[90,'Strategy stop']] as const){const s=account();tick(s,start+86400000);tick(s,start+86405000,price);assert.equal(s.positions.length,0);assert.equal(s.trades.at(-1)?.reason,reason)}const s=account();tick(s,start+5000,100,'close');assert.equal(s.positions.length,0)});
test('price-only policy retains daily risk exits',()=>{const s=account();s.dayBase=100200;tick(s,start+5000);assert.equal(s.halted,true);assert.equal(s.positions.length,0)});
test('migration removes only obsolete clock exits and retains risk/manual exits',()=>{for(const reason of ['Four-hour time exit','23:55 IST intraday close','Missed session end: closed on reconnect','Gold pre-break intraday close']){const s=account();s.positions[0].pendingExit=reason;ensureTeam(s);assert.equal(s.positions[0].pendingExit,undefined)}for(const reason of ['Manual close','$200 daily risk stop']){const s=account();s.positions[0].pendingExit=reason;s.legacy=structuredClone(s);ensureTeam(s);assert.equal(s.positions[0].pendingExit,reason);assert.equal(s.legacy.exitPolicy,'price-only');assert.equal(s.legacy.positions[0].pendingExit,reason)}});
test('gold carries through pre-break and closed market, then exits at fresh target',()=>{const s=account('XAU');for(const t of ['2026-10-05T20:55:00Z','2026-10-05T21:30:00Z']){tick(s,Date.parse(t));assert.equal(s.positions.length,1)}tick(s,Date.parse('2026-10-05T22:05:00Z'),120);assert.equal(s.positions.length,0);assert.equal(s.trades.at(-1)?.reason,'2R profit target')});
